### ISSUE TITLE
Visual Studio 2015 Build Error

### ISSUE THREAD

**Issue by phananhnhan** [leguims/PS4Macro.PES2018Lite#1] opened 2018-01-17 16:38 UTC
Can you share for me Visual Studio Version, which you use to code this project ?
When I build it, there are errors in AutomateMatch class.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1513	} expected	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	35	Active
Error	CS1043	{ or ; expected	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS1513	} expected	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS1002	; expected	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS1513	} expected	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS1043	{ or ; expected	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	35	Active
Error	CS1513	} expected	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	35	Active
Error	CS0200	Property or indexer 'AutomateMatch.StateAutomate' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	20	Active
Error	CS0200	Property or indexer 'AutomateMatch.TeamNumber' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	21	Active
Error	CS0161	'AutomateMatch.StateAutomate.get': not all code paths return a value	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS0201	Only assignment, call, increment, decrement, and new object expressions can be used as a statement	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS0103	The name 'set' does not exist in the current context	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS0103	The name 'value' does not exist in the current context	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS0103	The name 'value' does not exist in the current context	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	29	Active
Error	CS0161	'AutomateMatch.TeamNumber.get': not all code paths return a value	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	35	Active
Error	CS0201	Only assignment, call, increment, decrement, and new object expressions can be used as a statement	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	35	Active
Error	CS0201	Only assignment, call, increment, decrement, and new object expressions can be used as a statement	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	35	Active
Error	CS0200	Property or indexer 'AutomateMatch.StateAutomate' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	37	Active
Error	CS0200	Property or indexer 'AutomateMatch.StateAutomate' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	40	Active
Error	CS0200	Property or indexer 'AutomateMatch.TeamNumber' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	41	Active
Error	CS0200	Property or indexer 'AutomateMatch.StateAutomate' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	43	Active
Error	CS0200	Property or indexer 'AutomateMatch.StateAutomate' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	44	Active
Error	CS0200	Property or indexer 'AutomateMatch.StateAutomate' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	45	Active
Error	CS0200	Property or indexer 'AutomateMatch.StateAutomate' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	46	Active
Error	CS0200	Property or indexer 'AutomateMatch.StateAutomate' cannot be assigned to -- it is read only	PS4Macro.PES2018Lite	D:\GITHUB\PS4Macro.PES2018Lite-master\PS4Macro.PES2018Lite\MyClub\Sim\AutomateMatch.cs	47	Active

Can you help me ? Sorry for my English !

**Comment by leguims** [comment] 2018-01-17 19:24
My visual version is : Microsoft Visual Studio Community Version 15.5.3

The problem is that the PS4MacroAPI reference is not resolved in my repo.

You have to do these insctructions:
1. download ZIP of PS4Macro
2. copy file "PS4MacroAPI.dll" next to the project
3. Add reference to this file in the project.

It will compile after that.

I will explain that in readme soon.

That's ok for your english ! 😃

**Comment by leguims** [comment] 2018-01-17 22:37
Ok, I just added instruction "Install & Compile" to the "README.md". It explain where copy PS4MacroAPI.dll before compile solution.

**Closed as completed by leguims** 2018-01-17 22:37 UTC
Labels: bug, help wanted
